apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: depl-app
  name: depl-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: depl-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: depl-app
    spec:
      containers:
      - image: mahmoudkhairi/app
        name: app
        ports:
        - containerPort: 8000

apiVersion: v1
kind: Service
metadata:
  name: my-app-k8s-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 8000  # You can specify a port or let Kubernetes choose one
  selector:
    app: depl-app
